init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd Release
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin

# on build failure
on_failure:
  - ps: $root = Resolve-Path C:\OneNet\Log; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName to-publish }
